name: Frontend

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: Build
        run: |
          cd frontend
          pnpm install
          pnpm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name: Build
        run: |
          cd frontend
          pnpm install
          pnpm run build
